[package]
name = "whatsapp-desktop"
version = "0.4.2"
description = "WhatsApp Desktop for Linux"
authors = ["Vasco Guita <vasco@guita.org>"]
license = "MIT"
repository = "https://github.com/vascoguita/whatsapp-desktop"
edition = "2021"
rust-version = "1.77.2"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
log = "0.4"
percent-encoding = "2"
tauri = { version = "2.11.5", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-log = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-store = "2"

[patch.crates-io]
tauri-runtime-wry = { path = "vendor/tauri-runtime-wry" }
